### ISSUE TITLE
Fail while processing

### ISSUE THREAD

**Issue by pportiz** [Korto19/Cadastral_Divisions#3]
Failed triying to divide a polygon and showed me this message:

"Traceback (most recent call last):
File "D:/Usuarios/jose.ortiz.c/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Cadastral_Divisions-main\CadastralDivisions_algorithm.py", line 239, in processAlgorithm
frazioni = self.parameterAsBoolean(
AttributeError: 'CadastralDivisionsAlgorithm' object has no attribute 'parameterAsBoolean' "

Could you help me please?

Best Regards

**Comment by Korto19** [comment]
Thanks for the feedback. Have you tried with a clean profile? You should still give more information: QGIS version, operating system, any file with which to reproduce the error.
Best Regards

**Comment by pportiz** [comment]
You're welcome. 
QGis 3.6.1. Windows 10 Pro. I've tried with few different shapes (concaves and convexes). Do you want me to send you any of them? Thank you very much.

**Comment by Korto19** [comment]
Hi, if possible send me your files so I can check and let you know.
Best Regards

**Comment by pportiz** [comment]
Good morning. Could you tell me any email address for sending you the files, please?
Thanks and Best regards

**Comment by pportiz** [comment]
Good morning, again. I've put files here:
https://consigna.juntadeandalucia.es/d41262ed336dbc92449a8712cb061a2c 
There you'll find the polygon and the axis line (reference for the direction of cutting).
Thanks

**Comment by Korto19** [comment]
I have tried with your dataset and it works. Have you tried with newer QGIS versions? I made the plugin with 3.10.

**Comment by pportiz** [comment]
I'll try with 3.10. Thanks!!
Best Regards

**Comment by pportiz** [comment]
Good morning. Just tried with QGis3.10.14 and it Works but the divisions don't have exactly the same Surface; I've divided the same polygon I Sent to you. Is it possible to obtain three division with the same Surface? Best Regards.

**Comment by Korto19** [comment]
Hi, you are right in fact in 3 parts does not converge to a correct result, however you may have a particular situation, also because yours is a concave polygon and in such cases it may not converge to an exact result, as also indicated in the help page.
However you can divide the polygon into six parts and then merge to 2 by 2, this trick works on your polygon.

![image](https://user-images.githubusercontent.com/36882050/120344373-d15b5100-c2f9-11eb-982f-fe6dede2af32.png)
Best regards

**Comment by pportiz** [comment]
Good afternoon, Korto. Thank you very much. I'll try. Best regards.

**Comment by pportiz** [comment]
Hi again. I've tried and it Works but the two divisions on the right side seems to be not only one polygon after merging them. Could it be related with división process? Here you have image of my result.
https://consigna.juntadeandalucia.es/11d36665a41045f5e9fdf77377ac81b4 
Best Regards.

**Comment by Korto19** [comment]
I tried to merge the particles and this is the result. How did you put them together?
![image](https://user-images.githubusercontent.com/36882050/120512446-a8a38c00-c3cb-11eb-860f-6f6e26abeabe.png)
Best Regards

**Comment by pportiz** [comment]
Good morning
I've tried two ways:
"Combine selected spatial objets" and "Disolve" (geoprocess tools). None of them works.
Thanks and Best regards.

**Comment by pportiz** [comment]
Good morning
I've tried two ways:

"Combine selected spatial objets" and "Disolve" (geoprocess tools). None of them works. Wich one did you use?

Thanks and Best regards.

**Comment by Korto19** [comment]
Good afternoon,
sorry for the delay in answering you. usually in editing I select the two particles and "Merge Selected Features"
![image](https://user-images.githubusercontent.com/36882050/121555920-b2547180-ca13-11eb-852c-4c70fa78f3ee.png)
Best Regards

**Comment by pportiz** [comment]
Good morning.
No problem. 
That's the same I've used (said "combine" but it's really "merge"). 
Thank you!!
