### ISSUE TITLE
[pro memoria 2] la dividente deve essere un unico segmento

### ISSUE THREAD

**Issue by pigreco** [Korto19/Cadastral_Divisions#5]
Il plugin restituirà divisioni strane se la dividente fosse una polilinea invece che un unico segmento, ecco esempio:

![image](https://user-images.githubusercontent.com/7631137/175897640-aaaddeb6-d537-4ac3-a966-85376dbd59b8.png)

**Comment by Korto19** [comment]
Apportata modifica al minihelp ed al readme
